export { default as Tasks } from './Tasks';
export { default as Sidebar } from './Sidebar';
export { default as AddButton} from './AddButton';
export { default as Badge } from './Badge';
export { default as List } from './Sidebar/List.jsx';
export { default as AddTaskForm } from './Tasks/AddTaskForm.jsx';
export {default as Header} from './Header';
export {default as EditPopup} from './EditPopup';
export {default as MyButton} from './UI/button';
export {default as MyInput} from './UI/input';
export {default as MySelect} from './UI/select';
export {default as ColorPalette} from './ColorPalette';
export {default as CheckBoxCircle} from './UI/checkboxCircle';
export {default as Toggle} from './Toggle';
export {default as LoadingCircle} from './LoadingCircle';